# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCCar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateField(),
        ),
    ]
